{{- define "kubernetes-static-web.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
volumeMounts:
- mountPath: /var/cache/nginx/client_temp
  name: temp-client
- mountPath: /var/cache/nginx/proxy_temp
  name: temp-proxy
- mountPath: /var/cache/nginx/fastcgi_temp
  name: temp-fastcgi
{{- end -}}
