{{- define "kubernetes-static-web.container" -}}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
volumeMounts:
- mountPath: /var/cache/nginx/client_temp
  name: temp-client
{{- end -}}
