{{- include "helm-library.deployment" (list . "kubernetes-static-web.deployment") -}}
{{- define "kubernetes-static-web.deployment" -}}
spec:
  template:
    spec:
      volumes:
      - name: temp-client
        emptyDir: {}
      - name: temp-proxy
        emptyDir: {}
      - name: temp-fastcgi
        emptyDir: {}
      - name: temp-uwsgi
        emptyDir: {}
      containers:
      - {{ include "helm-library.container" (list . "kubernetes-static-web.container") }}
{{- end -}}
