environment: development
name: kubernetes-static-web
image: kubernetes-static-web

service:
  port: 80

container:
  imagePullPolicy: Always
  requestMemory: 40Mi
  requestCpu: 40m
  limitMemory: 40Mi
  limitCpu: 40m
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  port: 80

ingress:
  class: nginx
  host:
  certIssuer: letsencrypt

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000
